### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by weijy94** [ARPA-SIMC/fortrangis#13]
Hi, I'm running into some problems trying to build fortrangis. The "./configure --disable-doxydoc" seemed to work out fine, but when I ran "make check", errors occured:

[make_check.log](https://github.com/ARPA-SIMC/fortrangis/files/6933497/make_check.log)

The libfortrangis/test-suite.log shows:

[test-suite.log](https://github.com/ARPA-SIMC/fortrangis/files/6933491/test-suite.log)

I do have libshp.so.2 in my /usr/local/lib directory, so I wonder what caused this failure. Any advice would be much appreciated!

**Comment by dcesari** [comment]
Hi Weijy, usually `/usr/local/lib` is not in the default runtime library search path in Linux, maybe for security reasons, so you probably need to run `export LD_LIBRARY_PATH=/usr/local/lib` (or `LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` if it is already set elsewhere) in your user profile in order to use any program or library requiring libshp, such as fortrangis. However I admit that it is strange that the `./configure` step succeeded in your case.

Anyway, which distribution are you using? A cleaner approach could be to install shapelib and shapelib-dev(el) package from your distribution package manager, if it is available, in that case the library would likely go in /usr/lib(64) and there would be no need to perform the export indicated above.

**Comment by weijy94** [comment]
> Hi Weijy, usually `/usr/local/lib` is not in the default runtime library search path in Linux, maybe for security reasons, so you probably need to run `export LD_LIBRARY_PATH=/usr/local/lib` (or `LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` if it is already set elsewhere) in your user profile in order to use any program or library requiring libshp, such as fortrangis. However I admit that it is strange that the `./configure` step succeeded in your case.
> 
> Anyway, which distribution are you using? A cleaner approach could be to install shapelib and shapelib-dev(el) package from your distribution package manager, if it is available, in that case the library would likely go in /usr/lib(64) and there would be no need to perform the export indicated above.

Thank you, Dcesari. I did installed the shapelib from source code. The workaround I found was to directly copy the .so file to the .lib directory.
